### ISSUE TITLE
Login using Orcid doesn't work: CORS related error

### ISSUE THREAD

**Issue by typhainepl** [BioComputingUP/apicuron-issues#6]
**Describe the bug**
Login using Orcid doesn't work systematically. I have tried to log in on Chrome and Firefox, it worked on Firefox, but on Chrome I appear as not being logged in. One of my colleagues has the same issue but on both browsers.

**Screenshots**
![Screenshot 2024-09-02 at 16 35 40](https://github.com/user-attachments/assets/10003873-ade7-4721-aa9b-5999c07db1e6)
![Screenshot 2024-09-02 at 16 36 31](https://github.com/user-attachments/assets/cf574b07-0db6-492b-9b3c-9768bd762b04)

**Desktop (please complete the following information):**
 - OS: iOS Sonoma 14.6.1
 - Browser chrome v127.0.6533.89, firefox v129.0.2

**Comment by adelbke** [comment]
Thank you for submitting the issue.

From what I see in your stack trace and reproducing the bug:

- The error was triggered because you used [www.apicuron.org](www.apicuron.org) instead of [apicuron.org](apicuron.org).

I recommend using the latter URL by the time I push a fix. Thank you for pointing this out 🙏🏻.
